"""Init

Revision ID: eb5501c3f79f
Revises: 
Create Date: 2022-10-24 12:31:40.699079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5501c3f79f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbudget',
    sa.Column('fbudget_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.Column('costs', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('fbudget_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pbudget',
    sa.Column('pbudget_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.Column('costs', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pbudget_id')
    )
    op.create_table('u_o_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fbudget_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fbudget_id'], ['fbudget.fbudget_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('addatetimedress', sa.Date(), nullable=False),
    sa.Column('pbudget_id', sa.Integer(), nullable=False),
    sa.Column('fbudget_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fbudget_id'], ['fbudget.fbudget_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pbudget_id'], ['pbudget.pbudget_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('u_o_b')
    op.drop_table('pbudget')
    op.drop_table('users')
    op.drop_table('fbudget')
    # ### end Alembic commands ###
